/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VastuCheckerRouteImport } from './routes/vastu-checker'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StampDutyCalculatorRouteImport } from './routes/stamp-duty-calculator'
import { Route as RccSlabCalculatorRouteImport } from './routes/rcc-slab-calculator'
import { Route as PropertyCapitalGainsCalculatorRouteImport } from './routes/property-capital-gains-calculator'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PlotConverterRouteImport } from './routes/plot-converter'
import { Route as McdPropertyTaxCalculatorRouteImport } from './routes/mcd-property-tax-calculator'
import { Route as McdPropertyTaxCaNumberRouteImport } from './routes/mcd-property-tax-ca-number'
import { Route as MaterialCalculatorRouteImport } from './routes/material-calculator'
import { Route as InteriorRestyleRouteImport } from './routes/interior-restyle'
import { Route as IndexationCalculatorRouteImport } from './routes/indexation-calculator'
import { Route as GhmcPropertyTaxSearchByHouseNumberRouteImport } from './routes/ghmc-property-tax-search-by-house-number'
import { Route as GhmcPropertyTaxCalculatorRouteImport } from './routes/ghmc-property-tax-calculator'
import { Route as FloorPlan3dRouteImport } from './routes/floor-plan-3d'
import { Route as EmptyRoomStagerRouteImport } from './routes/empty-room-stager'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstructionCostCalculatorRouteImport } from './routes/construction-cost-calculator'
import { Route as ConcreteCalculatorRouteImport } from './routes/concrete-calculator'
import { Route as CementSandAggregateCalculatorRouteImport } from './routes/cement-sand-aggregate-calculator'
import { Route as BbmpPropertyTaxCalculatorRouteImport } from './routes/bbmp-property-tax-calculator'
import { Route as BbmpPropertyTax202627RouteImport } from './routes/bbmp-property-tax-2026-27'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StampDutyStateRouteImport } from './routes/stamp-duty/$state'
import { Route as ConstructionCostCityRouteImport } from './routes/construction-cost/$city'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const VastuCheckerRoute = VastuCheckerRouteImport.update({
  id: '/vastu-checker',
  path: '/vastu-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StampDutyCalculatorRoute = StampDutyCalculatorRouteImport.update({
  id: '/stamp-duty-calculator',
  path: '/stamp-duty-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const RccSlabCalculatorRoute = RccSlabCalculatorRouteImport.update({
  id: '/rcc-slab-calculator',
  path: '/rcc-slab-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyCapitalGainsCalculatorRoute =
  PropertyCapitalGainsCalculatorRouteImport.update({
    id: '/property-capital-gains-calculator',
    path: '/property-capital-gains-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotConverterRoute = PlotConverterRouteImport.update({
  id: '/plot-converter',
  path: '/plot-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const McdPropertyTaxCalculatorRoute =
  McdPropertyTaxCalculatorRouteImport.update({
    id: '/mcd-property-tax-calculator',
    path: '/mcd-property-tax-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const McdPropertyTaxCaNumberRoute = McdPropertyTaxCaNumberRouteImport.update({
  id: '/mcd-property-tax-ca-number',
  path: '/mcd-property-tax-ca-number',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialCalculatorRoute = MaterialCalculatorRouteImport.update({
  id: '/material-calculator',
  path: '/material-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorRestyleRoute = InteriorRestyleRouteImport.update({
  id: '/interior-restyle',
  path: '/interior-restyle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexationCalculatorRoute = IndexationCalculatorRouteImport.update({
  id: '/indexation-calculator',
  path: '/indexation-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const GhmcPropertyTaxSearchByHouseNumberRoute =
  GhmcPropertyTaxSearchByHouseNumberRouteImport.update({
    id: '/ghmc-property-tax-search-by-house-number',
    path: '/ghmc-property-tax-search-by-house-number',
    getParentRoute: () => rootRouteImport,
  } as any)
const GhmcPropertyTaxCalculatorRoute =
  GhmcPropertyTaxCalculatorRouteImport.update({
    id: '/ghmc-property-tax-calculator',
    path: '/ghmc-property-tax-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const FloorPlan3dRoute = FloorPlan3dRouteImport.update({
  id: '/floor-plan-3d',
  path: '/floor-plan-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyRoomStagerRoute = EmptyRoomStagerRouteImport.update({
  id: '/empty-room-stager',
  path: '/empty-room-stager',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionCostCalculatorRoute =
  ConstructionCostCalculatorRouteImport.update({
    id: '/construction-cost-calculator',
    path: '/construction-cost-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConcreteCalculatorRoute = ConcreteCalculatorRouteImport.update({
  id: '/concrete-calculator',
  path: '/concrete-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CementSandAggregateCalculatorRoute =
  CementSandAggregateCalculatorRouteImport.update({
    id: '/cement-sand-aggregate-calculator',
    path: '/cement-sand-aggregate-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const BbmpPropertyTaxCalculatorRoute =
  BbmpPropertyTaxCalculatorRouteImport.update({
    id: '/bbmp-property-tax-calculator',
    path: '/bbmp-property-tax-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const BbmpPropertyTax202627Route = BbmpPropertyTax202627RouteImport.update({
  id: '/bbmp-property-tax-2026-27',
  path: '/bbmp-property-tax-2026-27',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StampDutyStateRoute = StampDutyStateRouteImport.update({
  id: '/stamp-duty/$state',
  path: '/stamp-duty/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionCostCityRoute = ConstructionCostCityRouteImport.update({
  id: '/construction-cost/$city',
  path: '/construction-cost/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bbmp-property-tax-2026-27': typeof BbmpPropertyTax202627Route
  '/bbmp-property-tax-calculator': typeof BbmpPropertyTaxCalculatorRoute
  '/cement-sand-aggregate-calculator': typeof CementSandAggregateCalculatorRoute
  '/concrete-calculator': typeof ConcreteCalculatorRoute
  '/construction-cost-calculator': typeof ConstructionCostCalculatorRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/empty-room-stager': typeof EmptyRoomStagerRoute
  '/floor-plan-3d': typeof FloorPlan3dRoute
  '/ghmc-property-tax-calculator': typeof GhmcPropertyTaxCalculatorRoute
  '/ghmc-property-tax-search-by-house-number': typeof GhmcPropertyTaxSearchByHouseNumberRoute
  '/indexation-calculator': typeof IndexationCalculatorRoute
  '/interior-restyle': typeof InteriorRestyleRoute
  '/material-calculator': typeof MaterialCalculatorRoute
  '/mcd-property-tax-ca-number': typeof McdPropertyTaxCaNumberRoute
  '/mcd-property-tax-calculator': typeof McdPropertyTaxCalculatorRoute
  '/plot-converter': typeof PlotConverterRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-capital-gains-calculator': typeof PropertyCapitalGainsCalculatorRoute
  '/rcc-slab-calculator': typeof RccSlabCalculatorRoute
  '/stamp-duty-calculator': typeof StampDutyCalculatorRoute
  '/terms': typeof TermsRoute
  '/vastu-checker': typeof VastuCheckerRoute
  '/api/chat': typeof ApiChatRoute
  '/construction-cost/$city': typeof ConstructionCostCityRoute
  '/stamp-duty/$state': typeof StampDutyStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bbmp-property-tax-2026-27': typeof BbmpPropertyTax202627Route
  '/bbmp-property-tax-calculator': typeof BbmpPropertyTaxCalculatorRoute
  '/cement-sand-aggregate-calculator': typeof CementSandAggregateCalculatorRoute
  '/concrete-calculator': typeof ConcreteCalculatorRoute
  '/construction-cost-calculator': typeof ConstructionCostCalculatorRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/empty-room-stager': typeof EmptyRoomStagerRoute
  '/floor-plan-3d': typeof FloorPlan3dRoute
  '/ghmc-property-tax-calculator': typeof GhmcPropertyTaxCalculatorRoute
  '/ghmc-property-tax-search-by-house-number': typeof GhmcPropertyTaxSearchByHouseNumberRoute
  '/indexation-calculator': typeof IndexationCalculatorRoute
  '/interior-restyle': typeof InteriorRestyleRoute
  '/material-calculator': typeof MaterialCalculatorRoute
  '/mcd-property-tax-ca-number': typeof McdPropertyTaxCaNumberRoute
  '/mcd-property-tax-calculator': typeof McdPropertyTaxCalculatorRoute
  '/plot-converter': typeof PlotConverterRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-capital-gains-calculator': typeof PropertyCapitalGainsCalculatorRoute
  '/rcc-slab-calculator': typeof RccSlabCalculatorRoute
  '/stamp-duty-calculator': typeof StampDutyCalculatorRoute
  '/terms': typeof TermsRoute
  '/vastu-checker': typeof VastuCheckerRoute
  '/api/chat': typeof ApiChatRoute
  '/construction-cost/$city': typeof ConstructionCostCityRoute
  '/stamp-duty/$state': typeof StampDutyStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bbmp-property-tax-2026-27': typeof BbmpPropertyTax202627Route
  '/bbmp-property-tax-calculator': typeof BbmpPropertyTaxCalculatorRoute
  '/cement-sand-aggregate-calculator': typeof CementSandAggregateCalculatorRoute
  '/concrete-calculator': typeof ConcreteCalculatorRoute
  '/construction-cost-calculator': typeof ConstructionCostCalculatorRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/empty-room-stager': typeof EmptyRoomStagerRoute
  '/floor-plan-3d': typeof FloorPlan3dRoute
  '/ghmc-property-tax-calculator': typeof GhmcPropertyTaxCalculatorRoute
  '/ghmc-property-tax-search-by-house-number': typeof GhmcPropertyTaxSearchByHouseNumberRoute
  '/indexation-calculator': typeof IndexationCalculatorRoute
  '/interior-restyle': typeof InteriorRestyleRoute
  '/material-calculator': typeof MaterialCalculatorRoute
  '/mcd-property-tax-ca-number': typeof McdPropertyTaxCaNumberRoute
  '/mcd-property-tax-calculator': typeof McdPropertyTaxCalculatorRoute
  '/plot-converter': typeof PlotConverterRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-capital-gains-calculator': typeof PropertyCapitalGainsCalculatorRoute
  '/rcc-slab-calculator': typeof RccSlabCalculatorRoute
  '/stamp-duty-calculator': typeof StampDutyCalculatorRoute
  '/terms': typeof TermsRoute
  '/vastu-checker': typeof VastuCheckerRoute
  '/api/chat': typeof ApiChatRoute
  '/construction-cost/$city': typeof ConstructionCostCityRoute
  '/stamp-duty/$state': typeof StampDutyStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bbmp-property-tax-2026-27'
    | '/bbmp-property-tax-calculator'
    | '/cement-sand-aggregate-calculator'
    | '/concrete-calculator'
    | '/construction-cost-calculator'
    | '/contact'
    | '/disclaimer'
    | '/empty-room-stager'
    | '/floor-plan-3d'
    | '/ghmc-property-tax-calculator'
    | '/ghmc-property-tax-search-by-house-number'
    | '/indexation-calculator'
    | '/interior-restyle'
    | '/material-calculator'
    | '/mcd-property-tax-ca-number'
    | '/mcd-property-tax-calculator'
    | '/plot-converter'
    | '/privacy-policy'
    | '/property-capital-gains-calculator'
    | '/rcc-slab-calculator'
    | '/stamp-duty-calculator'
    | '/terms'
    | '/vastu-checker'
    | '/api/chat'
    | '/construction-cost/$city'
    | '/stamp-duty/$state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bbmp-property-tax-2026-27'
    | '/bbmp-property-tax-calculator'
    | '/cement-sand-aggregate-calculator'
    | '/concrete-calculator'
    | '/construction-cost-calculator'
    | '/contact'
    | '/disclaimer'
    | '/empty-room-stager'
    | '/floor-plan-3d'
    | '/ghmc-property-tax-calculator'
    | '/ghmc-property-tax-search-by-house-number'
    | '/indexation-calculator'
    | '/interior-restyle'
    | '/material-calculator'
    | '/mcd-property-tax-ca-number'
    | '/mcd-property-tax-calculator'
    | '/plot-converter'
    | '/privacy-policy'
    | '/property-capital-gains-calculator'
    | '/rcc-slab-calculator'
    | '/stamp-duty-calculator'
    | '/terms'
    | '/vastu-checker'
    | '/api/chat'
    | '/construction-cost/$city'
    | '/stamp-duty/$state'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bbmp-property-tax-2026-27'
    | '/bbmp-property-tax-calculator'
    | '/cement-sand-aggregate-calculator'
    | '/concrete-calculator'
    | '/construction-cost-calculator'
    | '/contact'
    | '/disclaimer'
    | '/empty-room-stager'
    | '/floor-plan-3d'
    | '/ghmc-property-tax-calculator'
    | '/ghmc-property-tax-search-by-house-number'
    | '/indexation-calculator'
    | '/interior-restyle'
    | '/material-calculator'
    | '/mcd-property-tax-ca-number'
    | '/mcd-property-tax-calculator'
    | '/plot-converter'
    | '/privacy-policy'
    | '/property-capital-gains-calculator'
    | '/rcc-slab-calculator'
    | '/stamp-duty-calculator'
    | '/terms'
    | '/vastu-checker'
    | '/api/chat'
    | '/construction-cost/$city'
    | '/stamp-duty/$state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BbmpPropertyTax202627Route: typeof BbmpPropertyTax202627Route
  BbmpPropertyTaxCalculatorRoute: typeof BbmpPropertyTaxCalculatorRoute
  CementSandAggregateCalculatorRoute: typeof CementSandAggregateCalculatorRoute
  ConcreteCalculatorRoute: typeof ConcreteCalculatorRoute
  ConstructionCostCalculatorRoute: typeof ConstructionCostCalculatorRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EmptyRoomStagerRoute: typeof EmptyRoomStagerRoute
  FloorPlan3dRoute: typeof FloorPlan3dRoute
  GhmcPropertyTaxCalculatorRoute: typeof GhmcPropertyTaxCalculatorRoute
  GhmcPropertyTaxSearchByHouseNumberRoute: typeof GhmcPropertyTaxSearchByHouseNumberRoute
  IndexationCalculatorRoute: typeof IndexationCalculatorRoute
  InteriorRestyleRoute: typeof InteriorRestyleRoute
  MaterialCalculatorRoute: typeof MaterialCalculatorRoute
  McdPropertyTaxCaNumberRoute: typeof McdPropertyTaxCaNumberRoute
  McdPropertyTaxCalculatorRoute: typeof McdPropertyTaxCalculatorRoute
  PlotConverterRoute: typeof PlotConverterRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PropertyCapitalGainsCalculatorRoute: typeof PropertyCapitalGainsCalculatorRoute
  RccSlabCalculatorRoute: typeof RccSlabCalculatorRoute
  StampDutyCalculatorRoute: typeof StampDutyCalculatorRoute
  TermsRoute: typeof TermsRoute
  VastuCheckerRoute: typeof VastuCheckerRoute
  ApiChatRoute: typeof ApiChatRoute
  ConstructionCostCityRoute: typeof ConstructionCostCityRoute
  StampDutyStateRoute: typeof StampDutyStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vastu-checker': {
      id: '/vastu-checker'
      path: '/vastu-checker'
      fullPath: '/vastu-checker'
      preLoaderRoute: typeof VastuCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stamp-duty-calculator': {
      id: '/stamp-duty-calculator'
      path: '/stamp-duty-calculator'
      fullPath: '/stamp-duty-calculator'
      preLoaderRoute: typeof StampDutyCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rcc-slab-calculator': {
      id: '/rcc-slab-calculator'
      path: '/rcc-slab-calculator'
      fullPath: '/rcc-slab-calculator'
      preLoaderRoute: typeof RccSlabCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-capital-gains-calculator': {
      id: '/property-capital-gains-calculator'
      path: '/property-capital-gains-calculator'
      fullPath: '/property-capital-gains-calculator'
      preLoaderRoute: typeof PropertyCapitalGainsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plot-converter': {
      id: '/plot-converter'
      path: '/plot-converter'
      fullPath: '/plot-converter'
      preLoaderRoute: typeof PlotConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcd-property-tax-calculator': {
      id: '/mcd-property-tax-calculator'
      path: '/mcd-property-tax-calculator'
      fullPath: '/mcd-property-tax-calculator'
      preLoaderRoute: typeof McdPropertyTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcd-property-tax-ca-number': {
      id: '/mcd-property-tax-ca-number'
      path: '/mcd-property-tax-ca-number'
      fullPath: '/mcd-property-tax-ca-number'
      preLoaderRoute: typeof McdPropertyTaxCaNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-calculator': {
      id: '/material-calculator'
      path: '/material-calculator'
      fullPath: '/material-calculator'
      preLoaderRoute: typeof MaterialCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-restyle': {
      id: '/interior-restyle'
      path: '/interior-restyle'
      fullPath: '/interior-restyle'
      preLoaderRoute: typeof InteriorRestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexation-calculator': {
      id: '/indexation-calculator'
      path: '/indexation-calculator'
      fullPath: '/indexation-calculator'
      preLoaderRoute: typeof IndexationCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghmc-property-tax-search-by-house-number': {
      id: '/ghmc-property-tax-search-by-house-number'
      path: '/ghmc-property-tax-search-by-house-number'
      fullPath: '/ghmc-property-tax-search-by-house-number'
      preLoaderRoute: typeof GhmcPropertyTaxSearchByHouseNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghmc-property-tax-calculator': {
      id: '/ghmc-property-tax-calculator'
      path: '/ghmc-property-tax-calculator'
      fullPath: '/ghmc-property-tax-calculator'
      preLoaderRoute: typeof GhmcPropertyTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-plan-3d': {
      id: '/floor-plan-3d'
      path: '/floor-plan-3d'
      fullPath: '/floor-plan-3d'
      preLoaderRoute: typeof FloorPlan3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty-room-stager': {
      id: '/empty-room-stager'
      path: '/empty-room-stager'
      fullPath: '/empty-room-stager'
      preLoaderRoute: typeof EmptyRoomStagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction-cost-calculator': {
      id: '/construction-cost-calculator'
      path: '/construction-cost-calculator'
      fullPath: '/construction-cost-calculator'
      preLoaderRoute: typeof ConstructionCostCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concrete-calculator': {
      id: '/concrete-calculator'
      path: '/concrete-calculator'
      fullPath: '/concrete-calculator'
      preLoaderRoute: typeof ConcreteCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cement-sand-aggregate-calculator': {
      id: '/cement-sand-aggregate-calculator'
      path: '/cement-sand-aggregate-calculator'
      fullPath: '/cement-sand-aggregate-calculator'
      preLoaderRoute: typeof CementSandAggregateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bbmp-property-tax-calculator': {
      id: '/bbmp-property-tax-calculator'
      path: '/bbmp-property-tax-calculator'
      fullPath: '/bbmp-property-tax-calculator'
      preLoaderRoute: typeof BbmpPropertyTaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bbmp-property-tax-2026-27': {
      id: '/bbmp-property-tax-2026-27'
      path: '/bbmp-property-tax-2026-27'
      fullPath: '/bbmp-property-tax-2026-27'
      preLoaderRoute: typeof BbmpPropertyTax202627RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stamp-duty/$state': {
      id: '/stamp-duty/$state'
      path: '/stamp-duty/$state'
      fullPath: '/stamp-duty/$state'
      preLoaderRoute: typeof StampDutyStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction-cost/$city': {
      id: '/construction-cost/$city'
      path: '/construction-cost/$city'
      fullPath: '/construction-cost/$city'
      preLoaderRoute: typeof ConstructionCostCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BbmpPropertyTax202627Route: BbmpPropertyTax202627Route,
  BbmpPropertyTaxCalculatorRoute: BbmpPropertyTaxCalculatorRoute,
  CementSandAggregateCalculatorRoute: CementSandAggregateCalculatorRoute,
  ConcreteCalculatorRoute: ConcreteCalculatorRoute,
  ConstructionCostCalculatorRoute: ConstructionCostCalculatorRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  EmptyRoomStagerRoute: EmptyRoomStagerRoute,
  FloorPlan3dRoute: FloorPlan3dRoute,
  GhmcPropertyTaxCalculatorRoute: GhmcPropertyTaxCalculatorRoute,
  GhmcPropertyTaxSearchByHouseNumberRoute:
    GhmcPropertyTaxSearchByHouseNumberRoute,
  IndexationCalculatorRoute: IndexationCalculatorRoute,
  InteriorRestyleRoute: InteriorRestyleRoute,
  MaterialCalculatorRoute: MaterialCalculatorRoute,
  McdPropertyTaxCaNumberRoute: McdPropertyTaxCaNumberRoute,
  McdPropertyTaxCalculatorRoute: McdPropertyTaxCalculatorRoute,
  PlotConverterRoute: PlotConverterRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PropertyCapitalGainsCalculatorRoute: PropertyCapitalGainsCalculatorRoute,
  RccSlabCalculatorRoute: RccSlabCalculatorRoute,
  StampDutyCalculatorRoute: StampDutyCalculatorRoute,
  TermsRoute: TermsRoute,
  VastuCheckerRoute: VastuCheckerRoute,
  ApiChatRoute: ApiChatRoute,
  ConstructionCostCityRoute: ConstructionCostCityRoute,
  StampDutyStateRoute: StampDutyStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
